name: my_chat_gpt
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  flutter_chat_ui: ^1.6.6
  flutter_markdown: ^0.6.10+3
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  dart_openai: ^1.8.0
  flutter_tts: ^3.6.3
  material_segmented_control: ^4.2.0

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

        
    
    
                                  #
    