name: my_chat_gpt
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  csv: ^6.0.0
  dart_openai: ^5.1.0
  flutter:
    sdk: flutter
  flutter_chat_ui:
    git: /Users/bobzhou/Developer/flutter/flutter_chat_ui
  flutter_riverpod: ^2.5.1
  flutter_tts: ^4.0.0
  hive: ^2.2.3
  loading_animation_widget: ^1.2.1
  macos_ui: ^2.0.5
  path_provider: ^2.1.1
  riverpod: ^2.5.1
  url_launcher: ^6.2.5
  uuid: ^4.1.0
  window_manager: ^0.3.8
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/awesome-chatgpt-prompts/prompts.csv
    - assets/awesome-chatgpt-prompts-zh/prompts-zh.json

  fonts:
    - family: RooneySans
      fonts:
        - asset: assets/fonts/RooneySansBlk.OTF
        - asset: assets/fonts/RooneySansBold.OTF
        - asset: assets/fonts/RooneySansLight.OTF
        - asset: assets/fonts/RooneySansMedium.OTF
        - asset: assets/fonts/RooneySansRegular.OTF
